db:
  image: postgres
mongo:
  image: mongo
  ports:
  - "27017:27017"
redis:
  image: redis
  volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
  ports:
  - "6379"
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
      - "3000:3000"
  links:
    - db
    - redis
    - mongo
worker:
  build: .
  command: bundle exec sidekiq -e development
  environment:
    RAILS_ENV: development
  links:
    - db
    - redis
    - mongo